package sofaScore.models.gameStatistics;

public enum LeagueStatisticsForAllTime3Periods {

	ALLPossessionBall_possession ("ALL,Possession,Ball_possession") ,
	ALLShotsTotal_shots ("ALL,Shots,Total_shots"),
	ALLShotsShots_on_target ("ALL,Shots,Shots_on_target") ,
	ALLShotsShots_off_target ("ALL,Shots,Shots_off_target"),
	ALLShotsBlocked_shots ("ALL,Shots,Blocked_shots") ,
	ALLTVDataCorner_kicks ("ALL,TVData,Corner_kicks"),
	ALLTVDataOffsides ("ALL,TVData,Offsides"),
	ALLTVDataFouls ("ALL,TVData,Fouls"),
	ALLTVDataYellow_cards ("ALL,TVData,Yellow_cards"),
	ALLTVDataRed_cards ("ALL,TVData,Red_cards") ,
	ALLShots_extraBig_chances ("ALL,Shots_extra,Big_chances"),
	ALLShots_extraBig_chances_missed ("ALL,Shots_extra,Big_chances_missed"),
	ALLShots_extraHit_woodwork ("ALL,Shots_extra,Hit_woodwork"),
	ALLShots_extraCounter_attacks ("ALL,Shots_extra,Counter_attacks"),
	ALLShots_extraCounter_attack_shots("ALL,Shots_extra,Counter_attack_shots"),
	ALLShots_extraCounter_attack_goals("ALL,Shots_extra,Counter_attack_goals"),
	ALLShots_extraShots_inside_box ("ALL,Shots_extra,Shots_inside_box"),
	ALLShots_extraShots_outside_box ("ALL,Shots_extra,Shots_outside_box") ,
	ALLShots_extraGoalkeeper_saves ("ALL,Shots_extra,Goalkeeper_saves"),
	ALLPassesPasses ("ALL,Passes,Passes") ,
	ALLPassesAccurate_passes ("ALL,Passes,Accurate_passes") ,
	ALLPassesLong_balls ("ALL,Passes,Long_balls") ,
	ALLPassesCrosses ("ALL,Passes,Crosses") ,
	ALLDuelsDribbles ("ALL,Duels,Dribbles") ,
	ALLDuelsPossession_lost ("ALL,Duels,Possession_lost"),
	ALLDuelsDuels_won ("ALL,Duels,Duels_won") ,
	ALLDuelsAerials_won ("ALL,Duels,Aerials_won") ,
	ALLDefendingTackles ("ALL,Defending,Tackles") ,
	ALLDefendingInterceptions ("ALL,Defending,Interceptions"),
	ALLDefendingClearances ("ALL,Defending,Clearances"),
	FirstHalfPossessionBall_possession ("FirstHalf,Possession,Ball_possession"),
	FirstHalfShotsTotal_shots ("FirstHalf,Shots,Total_shots"),
	FirstHalfShotsShots_on_target ("FirstHalf,Shots,Shots_on_target") ,
	FirstHalfShotsShots_off_target ("FirstHalf,Shots,Shots_off_target"),
	FirstHalfShotsBlocked_shots ("FirstHalf,Shots,Blocked_shots"),
	FirstHalfTVDataCorner_kicks ("FirstHalf,TVData,Corner_kicks"),
	FirstHalfTVDataOffsides ("FirstHalf,TVData,Offsides") ,
	FirstHalfTVDataFouls ("FirstHalf,TVData,Fouls"),
	FirstHalfTVDataYellow_cards ("FirstHalf,TVData,Yellow_cards") ,
	FirstHalfTVDataRed_cards ("FirstHalf,TVData,Red_cards"),	
	FirstHalfShots_extraBig_chances ("FirstHalf,Shots_extra,Big_chances"),
	FirstHalfShots_extraBig_chances_missed ("FirstHalf,Shots_extra,Big_chances_missed"),
	FirstHalfShots_extraHit_woodwork ("FirstHalf,Shots_extra,Hit_woodwork"),
	FirstHalfShots_extraCounter_attacks ("FirstHalf,Shots_extra,Counter_attacks"),
	FirstHalfShots_extraCounter_attack_shots("FirstHalf,Shots_extra,Counter_attack_shots"),
	FirstHalfShots_extraCounter_attack_goals("FirstHalf,Shots_extra,Counter_attack_goals"),
	FirstHalfShots_extraShots_inside_box ("FirstHalf,Shots_extra,Shots_inside_box") ,
	FirstHalfShots_extraShots_outside_box ("FirstHalf,Shots_extra,Shots_outside_box") ,
	FirstHalfShots_extraGoalkeeper_saves ("FirstHalf,Shots_extra,Goalkeeper_saves"),
	FirstHalfPassesPasses ("FirstHalf,Passes,Passes"),
	FirstHalfPassesAccurate_passes ("FirstHalf,Passes,Accurate_passes") ,
	FirstHalfPassesLong_balls ("FirstHalf,Passes,Long_balls") ,
	FirstHalfPassesCrosses ("FirstHalf,Passes,Crosses"),
	FirstHalfDuelsDribbles ("FirstHalf,Duels,Dribbles"),
	FirstHalfDuelsPossession_lost ("FirstHalf,Duels,Possession_lost"),
	FirstHalfDuelsDuels_won ("FirstHalf,Duels,Duels_won"),
	FirstHalfDuelsAerials_won ("FirstHalf,Duels,Aerials_won"),
	FirstHalfDefendingTackles ("FirstHalf,Defending,Tackles") ,
	FirstHalfDefendingInterceptions ("FirstHalf,Defending,Interceptions"),
	FirstHalfDefendingClearances ("FirstHalf,Defending,Clearances") ,
	SecondHalfPossessionBall_possession ("SecondHalf,Possession,Ball_possession"),
	SecondHalfShotsTotal_shots ("SecondHalf,Shots,Total_shots"),
	SecondHalfShotsShots_on_target ("SecondHalf,Shots,Shots_on_target") ,
	SecondHalfShotsShots_off_target ("SecondHalf,Shots,Shots_off_target") ,
	SecondHalfShotsBlocked_shots ("SecondHalf,Shots,Blocked_shots") ,
	SecondHalfTVDataCorner_kicks ("SecondHalf,TVData,Corner_kicks") ,
	SecondHalfTVDataOffsides ("SecondHalf,TVData,Offsides"),
	SecondHalfTVDataFouls ("SecondHalf,TVData,Fouls"),
	SecondHalfTVDataYellow_cards ("SecondHalf,TVData,Yellow_cards"),
	SecondHalfTVDataRed_cards ("SecondHalf,TVData,Red_cards"),
	SecondHalfShots_extraBig_chances ("SecondHalf,Shots_extra,Big_chances"),
	SecondHalfShots_extraBig_chances_missed ("SecondHalf,Shots_extra,Big_chances_missed"),
	SecondHalfShots_extraHit_woodwork ("SecondHalf,Shots_extra,Hit_woodwork"),
	SecondHalfShots_extraCounter_attacks ("SecondHalf,Shots_extra,Counter_attacks") ,
	SecondHalfShots_extraCounter_attack_shots("SecondHalf,Shots_extra,Counter_attack_shots"),
	SecondHalfShots_extraCounter_attack_goals("SecondHalf,Shots_extra,Counter_attack_goals"),
	SecondHalfShots_extraShots_inside_box ("SecondHalf,Shots_extra,Shots_inside_box"),
	SecondHalfShots_extraShots_outside_box ("SecondHalf,Shots_extra,Shots_outside_box"),
	SecondHalfShots_extraGoalkeeper_saves ("SecondHalf,Shots_extra,Goalkeeper_saves"),
	SecondHalfPassesPasses ("SecondHalf,Passes,Passes"),
	SecondHalfPassesAccurate_passes ("SecondHalf,Passes,Accurate_passes"),
	SecondHalfPassesLong_balls ("SecondHalf,Passes,Long_balls"),
	SecondHalfPassesCrosses ("SecondHalf,Passes,Crosses"),
	SecondHalfDuelsDribbles ("SecondHalf,Duels,Dribbles") ,
	SecondHalfDuelsPossession_lost ("SecondHalf,Duels,Possession_lost"),
	SecondHalfDuelsDuels_won ("SecondHalf,Duels,Duels_won"),
	SecondHalfDuelsAerials_won ("SecondHalf,Duels,Aerials_won"),
	SecondHalfDefendingTackles ("SecondHalf,Defending,Tackles"),
	SecondHalfDefendingInterceptions ("SecondHalf,Defending,Interceptions"),
	SecondHalfDefendingClearances ("SecondHalf,Defending,Clearances");
	
	private String value;
	
	private LeagueStatisticsForAllTime3Periods(String value) {
		this.value = value;
	}
	
	public String value() {
		return this.value;
	}
}
