package sofaScore.models.gameStatistics;

public enum LeagueStatisticsForAllTime5Periods {
	ALLPossessionBallpossession ("ALL,Possession,Ball possession") ,
	ALLShotsTotalshots ("ALL,Shots,Total shots"),
	ALLShotsShotsontarget ("ALL,Shots,Shots on target") ,
	ALLShotsShotsofftarget ("ALL,Shots,Shots off target"),
	ALLShotsBlockedshots ("ALL,Shots,Blocked shots") ,
	ALLTVDataCornerkicks ("ALL,TVData,Corner kicks"),
	ALLTVDataOffsides ("ALL,TVData,Offsides"),
	ALLTVDataFouls ("ALL,TVData,Fouls"),
	ALLTVDataYellowcards ("ALL,TVData,Yellow cards"),
	ALLTVDataRedcards ("ALL,TVData,Red cards") ,
	ALLShotsextraBigchances ("ALL,Shots extra,Big chances"),
	ALLShotsextraBigchancesmissed ("ALL,Shots extra,Big chances missed"),
	ALLShotsextraHitwoodwork ("ALL,Shots extra,Hit woodwork"),
	ALLShotsextraCounterattacks ("ALL,Shots extra,Counter attacks"),
	ALLShotsextraCounterattackshots("ALL,Shots extra,Counter attack shots"),
	ALLShotsextraCounterattackgoals("ALL,Shots extra,Counter attack goals"),
	ALLShotsextraShotsinsidebox ("ALL,Shots extra,Shots inside box"),
	ALLShotsextraShotsoutsidebox ("ALL,Shots extra,Shots outside box") ,
	ALLShotsextraGoalkeepersaves ("ALL,Shots extra,Goalkeeper saves"),
	ALLPassesPasses ("ALL,Passes,Passes") ,
	ALLPassesAccuratepasses ("ALL,Passes,Accurate passes") ,
	ALLPassesLongballs ("ALL,Passes,Long balls") ,
	ALLPassesCrosses ("ALL,Passes,Crosses") ,
	ALLDuelsDribbles ("ALL,Duels,Dribbles") ,
	ALLDuelsPossessionlost ("ALL,Duels,Possession lost"),
	ALLDuelsDuelswon ("ALL,Duels,Duels won") ,
	ALLDuelsAerialswon ("ALL,Duels,Aerials won") ,
	ALLDefendingTackles ("ALL,Defending,Tackles") ,
	ALLDefendingInterceptions ("ALL,Defending,Interceptions"),
	ALLDefendingClearances ("ALL,Defending,Clearances"),
	FirstHalfPossessionBallpossession ("FirstHalf,Possession,Ball possession"),
	FirstHalfShotsTotalshots ("FirstHalf,Shots,Total shots"),
	FirstHalfShotsShotsontarget ("FirstHalf,Shots,Shots on target") ,
	FirstHalfShotsShotsofftarget ("FirstHalf,Shots,Shots off target"),
	FirstHalfShotsBlockedshots ("FirstHalf,Shots,Blocked shots"),
	FirstHalfTVDataCornerkicks ("FirstHalf,TVData,Corner kicks"),
	FirstHalfTVDataOffsides ("FirstHalf,TVData,Offsides") ,
	FirstHalfTVDataYellowcards ("FirstHalf,TVData,Yellow cards") ,
	FirstHalfTVDataRedcards ("FirstHalf,TVData,Red cards"),	
	FirstHalfShotsextraBigchances ("FirstHalf,Shots extra,Big chances"),
	FirstHalfShotsextraBigchancesmissed ("FirstHalf,Shots extra,Big chances missed"),
	FirstHalfShotsextraHitwoodwork ("FirstHalf,Shots extra,Hit woodwork"),
	FirstHalfShotsextraCounterattacks ("FirstHalf,Shots extra,Counter attacks"),
	FirstHalfShotsextraCounterattackshots("FirstHalf,Shots extra,Counter attack shots"),
	FirstHalfShotsextraCounterattackgoals("FirstHalf,Shots extra,Counter attack goals"),
	FirstHalfShotsextraShotsinsidebox ("FirstHalf,Shots extra,Shots inside box") ,
	FirstHalfShotsextraShotsoutsidebox ("FirstHalf,Shots extra,Shots outside box") ,
	FirstHalfShotsextraGoalkeepersaves ("FirstHalf,Shots extra,Goalkeeper saves"),
	FirstHalfPassesPasses ("FirstHalf,Passes,Passes"),
	FirstHalfPassesAccuratepasses ("FirstHalf,Passes,Accurate passes") ,
	FirstHalfPassesLongballs ("FirstHalf,Passes,Long balls") ,
	FirstHalfPassesCrosses ("FirstHalf,Passes,Crosses"),
	FirstHalfDuelsDribbles ("FirstHalf,Duels,Dribbles"),
	FirstHalfDuelsPossessionlost ("FirstHalf,Duels,Possession lost"),
	FirstHalfDuelsDuelswon ("FirstHalf,Duels,Duels won"),
	FirstHalfDuelsAerialswon ("FirstHalf,Duels,Aerials won"),
	FirstHalfDefendingTackles ("FirstHalf,Defending,Tackles") ,
	FirstHalfDefendingInterceptions ("FirstHalf,Defending,Interceptions"),
	FirstHalfDefendingClearances ("FirstHalf,Defending,Clearances") ,
	SecondHalfPossessionBallpossession ("SecondHalf,Possession,Ball possession"),
	SecondHalfShotsTotalshots ("SecondHalf,Shots,Total shots"),
	SecondHalfShotsShotsontarget ("SecondHalf,Shots,Shots on target") ,
	SecondHalfShotsShotsofftarget ("SecondHalf,Shots,Shots off target") ,
	SecondHalfShotsBlockedshots ("SecondHalf,Shots,Blocked shots") ,
	SecondHalfTVDataCornerkicks ("SecondHalf,TVData,Corner kicks") ,
	SecondHalfTVDataOffsides ("SecondHalf,TVData,Offsides"),
	SecondHalfTVDataYellowcards ("SecondHalf,TVData,Yellow cards"),
	SecondHalfTVDataRedcards ("SecondHalf,TVData,Red cards"),
	SecondHalfShotsextraBigchances ("SecondHalf,Shots extra,Big chances"),
	SecondHalfShotsextraBigchancesmissed ("SecondHalf,Shots extra,Big chances missed"),
	SecondHalfShotsextraHitwoodwork ("SecondHalf,Shots extra,Hit woodwork"),
	SecondHalfShotsextraCounterattacks ("SecondHalf,Shots extra,Counter attacks") ,
	SecondHalfShotsextraCounterattackshots("SecondHalf,Shots extra,Counter attack shots"),
	SecondHalfShotsextraCounterattackgoals("SecondHalf,Shots extra,Counter attack goals"),
	SecondHalfShotsextraShotsinsidebox ("SecondHalf,Shots extra,Shots inside box"),
	SecondHalfShotsextraShotsoutsidebox ("SecondHalf,Shots extra,Shots outside box"),
	SecondHalfShotsextraGoalkeepersaves ("SecondHalf,Shots extra,Goalkeeper saves"),
	SecondHalfPassesPasses ("SecondHalf,Passes,Passes"),
	SecondHalfPassesAccuratepasses ("SecondHalf,Passes,Accurate passes"),
	SecondHalfPassesLongballs ("SecondHalf,Passes,Long balls"),
	SecondHalfPassesCrosses ("SecondHalf,Passes,Crosses"),
	SecondHalfDuelsDribbles ("SecondHalf,Duels,Dribbles") ,
	SecondHalfDuelsPossessionlost ("SecondHalf,Duels,Possession lost"),
	SecondHalfDuelsDuelswon ("SecondHalf,Duels,Duels won"),
	SecondHalfDuelsAerialswon ("SecondHalf,Duels,Aerials won"),
	SecondHalfDefendingTackles ("SecondHalf,Defending,Tackles"),
	SecondHalfDefendingInterceptions ("SecondHalf,Defending,Interceptions"),
	SecondHalfDefendingClearances ("SecondHalf,Defending,Clearances"),
	ET1PossessionBallpossession ("ALL,Possession,Ball possession") ,
	ET1ShotsTotalshots ("ET1,Shots,Total shots"),
	ET1ShotsShotsontarget ("ET1,Shots,Shots on target") ,
	ET1ShotsShotsofftarget ("ET1,Shots,Shots off target"),
	ET1ShotsBlockedshots ("ET1,Shots,Blocked shots") ,
	ET1TVDataCornerkicks ("ET1,TVData,Corner kicks"),
	ET1TVDataOffsides ("ET1,TVData,Offsides"),
	ET1TVDataFouls ("ET1,TVData,Fouls"),
	ET1TVDataYellowcards ("ET1,TVData,Yellow cards"),
	ET1TVDataRedcards ("ET1,TVData,Red cards") ,
	ET1ShotsextraBigchances ("ET1,Shots extra,Big chances"),
	ET1ShotsextraBigchancesmissed ("ET1,Shots extra,Big chances missed"),
	ET1ShotsextraHitwoodwork ("ET1,Shots extra,Hit woodwork"),
	ET1ShotsextraCounterattacks ("ET1,Shots extra,Counter attacks"),
	ET1ShotsextraCounterattackshots("ET1,Shots extra,Counter attack shots"),
	ET1ShotsextraCounterattackgoals("ET1,Shots extra,Counter attack goals"),
	ET1ShotsextraShotsinsidebox ("ET1,Shots extra,Shots inside box"),
	ET1ShotsextraShotsoutsidebox ("ET1,Shots extra,Shots outside box") ,
	ET1ShotsextraGoalkeepersaves ("ET1,Shots extra,Goalkeeper saves"),
	ET1PassesPasses ("ET1,Passes,Passes") ,
	ET1PassesAccuratepasses ("ET1,Passes,Accurate passes") ,
	ET1PassesLongballs ("ET1,Passes,Long balls") ,
	ET1PassesCrosses ("ET1,Passes,Crosses") ,
	ET1DuelsDribbles ("ET1,Duels,Dribbles") ,
	ET1DuelsPossessionlost ("ET1,Duels,Possession lost"),
	ET1DuelsDuelswon ("ET1,Duels,Duels won") ,
	ET1DuelsAerialswon ("ET1,Duels,Aerials won") ,
	ET1DefendingTackles ("ET1,Defending,Tackles") ,
	ET1DefendingInterceptions ("ET1,Defending,Interceptions"),
	ET1DefendingClearances ("ET1,Defending,Clearances"),
	ET2PossessionBallpossession ("ET2,Possession,Ball possession") ,
	ET2ShotsTotalshots ("ET2,Shots,Total shots"),
	ET2ShotsShotsontarget ("ET2,Shots,Shots on target") ,
	ET2ShotsShotsofftarget ("ET2,Shots,Shots off target"),
	ET2ShotsBlockedshots ("ET2,Shots,Blocked shots") ,
	ET2TVDataCornerkicks ("ET2,TVData,Corner kicks"),
	ET2TVDataOffsides ("ET2,TVData,Offsides"),
	ET2TVDataFouls ("ET2,TVData,Fouls"),
	ET2TVDataYellowcards ("ET2,TVData,Yellow cards"),
	ET2TVDataRedcards ("ET2,TVData,Red cards") ,
	ET2ShotsextraBigchances ("ET2,Shots extra,Big chances"),
	ET2ShotsextraBigchancesmissed ("ET2,Shots extra,Big chances missed"),
	ET2ShotsextraHitwoodwork ("ET2,Shots extra,Hit woodwork"),
	ET2ShotsextraCounterattacks ("ET2,Shots extra,Counter attacks"),
	ET2ShotsextraCounterattackshots("ET2,Shots extra,Counter attack shots"),
	ET2ShotsextraCounterattackgoals("ET2,Shots extra,Counter attack goals"),
	ET2ShotsextraShotsinsidebox ("ET2,Shots extra,Shots inside box"),
	ET2ShotsextraShotsoutsidebox ("ET2,Shots extra,Shots outside box") ,
	ET2ShotsextraGoalkeepersaves ("ET2,Shots extra,Goalkeeper saves"),
	ET2PassesPasses ("ET2,Passes,Passes") ,
	ET2PassesAccuratepasses ("ET2,Passes,Accurate passes") ,
	ET2PassesLongballs ("ET2,Passes,Long balls") ,
	ET2PassesCrosses ("ET2,Passes,Crosses") ,
	ET2DuelsDribbles ("ET2,Duels,Dribbles") ,
	ET2DuelsPossessionlost ("ET2,Duels,Possession lost"),
	ET2DuelsDuelswon ("ET2,Duels,Duels won") ,
	ET2DuelsAerialswon ("ET2,Duels,Aerials won") ,
	ET2DefendingTackles ("ET2,Defending,Tackles") ,
	ET2DefendingInterceptions ("ET2,Defending,Interceptions"),
	ET2DefendingClearances ("ET2,Defending,Clearances");
	
	private String value;
	
	private LeagueStatisticsForAllTime5Periods(String value) {
		this.value = value;
	}
	
	public String value() {
		return this.value;
	}
}
